[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/imgs/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
